const channelsDataBase = [
  {
    name: 'storage_2',
    ua_name: 'Склад №2 вулиця',
    location: 'storage',
    position: 1,
    channelNumber: 618304,
    minT: -3,
    maxT: 26,
  },
  {
    name: 'storage_3',
    ua_name: 'Склад №3 вулиця',
    location: 'storage',
    position: 2,
    channelNumber: 618586,
    minT: -3,
    maxT: 26,
  },
  {
    name: 'storage_5',
    ua_name: 'Склад №5 вулиця',
    location: 'storage',
    position: 3,
    channelNumber: 618723,
    minT: -3,
    maxT: 26,
  },
  {
    name: 'storage_6',
    ua_name: 'Склад №6 вулиця',
    location: 'storage',
    position: 4,
    channelNumber: 618751,
    minT: -3,
    maxT: 26,
  },
  {
    name: 'storage_7',
    ua_name: 'Склад №7 вулиця',
    location: 'storage',
    position: 5,
    channelNumber: 618770,
    minT: -3,
    maxT: 26,
  },
  {
    name: 'storage_8',
    ua_name: 'Склад №8 вулиця',
    location: 'storage',
    position: 6,
    channelNumber: 618841,
    minT: -3,
    maxT: 26,
  },
  {
    name: 'ramp_storage',
    ua_name: 'Склад рампа',
    location: 'storage',
    position: 7,
    channelNumber: 630672,
    minT: -3,
    maxT: 26,
  },
  {
    name: 'lower_storage',
    ua_name: 'Нижній склад',
    location: 'storage',
    position: 8,
    channelNumber: 630573,
    minT: -3,
    maxT: 26,
  },

  {
    name: 'fridge_1',
    ua_name: 'Холодильник №1',
    location: 'fridge',
    position: 9,
    channelNumber: 635829,
    minT: 0,
    maxT: 26,
  },

  {
    name: 'fridge_2',
    ua_name: 'Холодильник №2',
    location: 'fridge',
    position: 10,
    channelNumber: 634234,
    minT: 0,
    maxT: 26,
  },

  {
    name: 'fridge_3',
    ua_name: 'Холодильник №3',
    location: 'fridge',
    position: 11,
    channelNumber: 630834,
    minT: 0,
    maxT: 26,
  },
  {
    name: 'near_fridge_1',
    ua_name: 'Біля холод. №1',
    location: 'packing_area',
    position: 12,
    channelNumber: 635841,
    minT: -10,
    maxT: 26,
  },
  {
    name: 'near_fridge_2',
    ua_name: 'Біля холод. №2',
    location: 'packing_area',
    position: 13,
    channelNumber: 635807,
    minT: -10,
    maxT: 26,
  },
  {
    name: 'near_fridge_3',
    ua_name: 'Біля холод. №3',
    location: 'packing_area',
    position: 14,
    channelNumber: 634208,
    minT: -10,
    maxT: 26,
  },
  {
    name: 'greenhouse_1a',
    ua_name: 'Теплиця 1A',
    location: 'greenhouse',
    position: 15,
    channelNumber: 967984,
    minT: -10,
    maxT: 26,
  },
  {
    name: 'greenhouse_1b',
    ua_name: 'Теплиця 1B',
    location: 'greenhouse',
    position: 16,
    channelNumber: 972793,
    minT: -10,
    maxT: 26,
  },
  {
    name: 'greenhouse_2a',
    ua_name: 'Теплиця 2A',
    location: 'greenhouse',
    position: 17,
    channelNumber: 986377,
    minT: -10,
    maxT: 26,
  },
  {
    name: 'greenhouse_2b',
    ua_name: 'Теплиця 2B',
    location: 'greenhouse',
    position: 18,
    channelNumber: 987091,
    minT: -10,
    maxT: 26,
  },
];

export default channelsDataBase;
